name: Build Unity WebGL

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: 'Commit message for Unity build update'
        required: true
        default: 'chore: update WebGL build'
        type: string

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      # 1) Unity 프로젝트 체크아웃
      - name: Checkout Unity project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      # 2) WebGL 빌드 (루트 기준)
      - name: Build WebGL
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: .
          unityVersion: '2022.3.62f1'
          targetPlatform: WebGL

      # 3) 디버그: 실제 build 폴더 구조 확인
      - name: Debug build output
        run: |
          echo ">>> build 디렉토리 구조"
          ls -R build

      # 4) UnityBuild 레포 체크아웃
      - name: Checkout UnityBuild repo
        uses: actions/checkout@v4
        with:
          repository: Thedum2/GalaShow_UnityBuild
          token: ${{ secrets.GALASHOW_TOKEN }}
          ref: develop
          path: unitybuild
          fetch-depth: 0

      # 5) 이전 빌드 파일 전부 제거
      - name: Clear old build files
        run: rm -rf unitybuild/*

      # 6) WebGL/WebGL/Build 폴더의 파일만 복사
      - name: Copy WebGL build files into UnityBuild root
        run: |
          cp build/WebGL/WebGL/Build/* unitybuild/

      # 7) 커밋 & develop 브랜치에 푸시
      - name: Commit & push WebGL build
        working-directory: unitybuild
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "${{ inputs.commit_message }}"
            git push origin develop
          fi
