name: Build Unity WebGL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Unity project
        uses: actions/checkout@v3

      - name: Set up Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2021.3.62f1
          targetPlatform: WebGL

      - name: Upload WebGL build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: unity-webgl-build
          path: build/WebGL